version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /arachnid
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /core
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /rat
    schedule:
      interval: daily